del list.txt
del formatcheck.txt
del cuesheet.cue
del input.mp3
del input.m4b
del metadata.txt
del Cover.jpg
del meta1.txt
del meta2.txt
del meta3.txt
del metadatatemp.txt
del fileList.txt
del inputmeta.txt
